on: [push]
name: Mirror
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: yesolutions/mirror-action@master
      with:
        REMOTE: 'git@e.coding.net:llop18870/alas/AzurLaneAutoScript.git'
        GIT_SSH_PRIVATE_KEY: ${{ secrets.CODING_SSH_PRIVATE_KEY }}
        GIT_SSH_NO_VERIFY_HOST: "true"
